name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

    - name: Run linting
      run: composer lint

    - name: Run static analysis
      run: composer stan

    - name: Run test suite
      env: # Or as an environment variable
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
      run: composer test

    - uses: actions/upload-artifact@v1
      with:
          name: infection.log
          path: tests/reports/infection.log
